### ISSUE TITLE
Planned Changes Theory

### ISSUE THREAD

**Issue by dhershman1** [dhershman1/simply_valid#5]
I want to tweak the build plan a bit.

Currently it builds out by type which is sort of pointless.

I want to have the library build out as a actual lib you can simply breakdown and use the functions of.

For instance:
```js
import { isNumber, isPositive } from 'simply_valid'

isPositive(1) // => true
isNumber(1) // => true
```

But also have the ability to do this:

```js
import { isNumber, isPositive, validate } from 'simply_valid'

isPositive(1) // => true
isNumber(1) // => true

const isValid = validate({
  schema: ['isPositive']
})

isValid(1) // => true
```

But this also begs the question, do we stop using the strings? And have them send in the functions they want to use? Like this:

```js
import { isNumber, isPositive, validate } from 'simply_valid'

const isValid = validate({
  schema: [isPositive, isNumber]
})

isValid(1) // => true
isValid(-1) // => false
```

Several approaches to take in the thought process of this, or maybe we don't change anything at all about the flow? Is it fine as is?

**Comment by smoaty** [comment]
I'm a fan of option 3, personally, but I don't have a strong feeling about it. I think string is probably fine, but non string is a bit more clear and clean imo.

**Comment by Glen-Cocoa** [comment]
it makes sense to me to pass in a reference to the functions themselves and not their string representative
